# Generated by Django 5.1.6 on 2025-02-23 10:28

import account.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_coursefield_groopname_subscribeplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='OTP',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.CreateModel(
            name='PaymentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('banner_img', models.ImageField(upload_to=account.models.payment_product_banner)),
                ('desc', models.TextField()),
                ('price', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('thank_note', models.TextField()),
                ('redirect_url', models.URLField()),
                ('googel_pixel_id', models.CharField(max_length=150, null=True)),
                ('facebook_pixel_id', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('gst_info', models.BooleanField(default=False)),
                ('media_url', models.FileField(upload_to=account.models.payment_product)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
