# Generated by Django 5.1.6 on 2025-02-23 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_user_otp_paymentlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentlink',
            name='facebook_pixel_id',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
