# Generated by Django 5.1.6 on 2025-02-23 14:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_paymentlink_facebook_pixel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentlink',
            name='product_uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
