# Generated by Django 5.1.6 on 2025-02-28 06:52

import account.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_customer_paymentproductque'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='subscribe_end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='subscribe_start',
            field=models.DateTimeField(auto_now_add=True, default='1994-10-10 12.00'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CustomerProductAns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=300, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.customer')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.paymentproductque')),
            ],
        ),
        migrations.CreateModel(
            name='EmailMarketing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_csv_file', models.FileField(upload_to=account.models.email_market)),
                ('desc', models.TextField(null=True)),
                ('send_file', models.FileField(upload_to=account.models.email_send_file)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WhatappMarketing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_csv_file', models.FileField(upload_to=account.models.whatapp_market)),
                ('desc', models.TextField(null=True)),
                ('send_file', models.FileField(upload_to=account.models.whatapp_send_file)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
