# Generated by Django 5.1.6 on 2025-03-04 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_customer_subscribe_end_customer_subscribe_start_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='RazorPayPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(help_text='Unique Razorpay transaction ID', max_length=100, unique=True)),
                ('order_id', models.CharField(help_text='Associated order ID from Razorpay', max_length=100)),
                ('payment_id', models.CharField(help_text='Razorpay payment ID', max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount in INR', max_digits=10)),
                ('currency', models.CharField(default='INR', help_text='Currency of transaction', max_length=10)),
                ('status', models.CharField(choices=[('created', 'Created'), ('authorized', 'Authorized'), ('captured', 'Captured'), ('failed', 'Failed'), ('refunded', 'Refunded')], help_text='Transaction status', max_length=20)),
                ('payment_method', models.CharField(choices=[('card', 'Card'), ('netbanking', 'Net Banking'), ('upi', 'UPI'), ('wallet', 'Wallet'), ('emi', 'EMI'), ('bank_transfer', 'Bank Transfer')], help_text='Payment method used', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Transaction creation time')),
                ('captured_at', models.DateTimeField(blank=True, help_text='Payment capture timestamp', null=True)),
                ('refund_status', models.BooleanField(default=False, help_text='True if refunded')),
                ('fee', models.DecimalField(blank=True, decimal_places=2, help_text='Razorpay transaction fee', max_digits=10, null=True)),
                ('tax', models.DecimalField(blank=True, decimal_places=2, help_text='Tax amount deducted', max_digits=10, null=True)),
                ('card_last4', models.CharField(blank=True, help_text='Last 4 digits of card (if applicable)', max_length=4, null=True)),
                ('bank_name', models.CharField(blank=True, help_text='Bank name (if net banking)', max_length=100, null=True)),
                ('upi_id', models.CharField(blank=True, help_text='UPI ID (if paid via UPI)', max_length=100, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional transaction notes', null=True)),
                ('webhook_response', models.JSONField(blank=True, help_text='Raw webhook response from Razorpay', null=True)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(help_text='Razorpay payment ID', on_delete=django.db.models.deletion.DO_NOTHING, to='account.customer', unique=True)),
            ],
        ),
    ]
