# Generated by Django 5.1.6 on 2025-03-07 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_razorpaypayment_captured_razorpaypayment_reciept_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='razorpaypayment',
            name='user',
            field=models.ForeignKey(help_text='Razorpay payment ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='account.customer'),
        ),
    ]
