# Generated by Django 5.1.6 on 2025-03-07 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_razorpaypayment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='razorpaypayment',
            name='payment_id',
            field=models.CharField(help_text='Razorpay payment ID', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='razorpaypayment',
            name='transaction_id',
            field=models.CharField(help_text='Unique Razorpay transaction ID', max_length=100, null=True),
        ),
    ]
