# Generated by Django 5.1.6 on 2025-03-08 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_alter_user_email_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribeplan',
            name='duration_months',
        ),
        migrations.RemoveField(
            model_name='subscribeplan',
            name='duration_years',
        ),
        migrations.AddField(
            model_name='subscribeplan',
            name='life_time',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscribeplan',
            name='plan_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='TelegramChannelProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('desc', models.TextField()),
                ('price', models.IntegerField(null=True)),
                ('discount', models.IntegerField(null=True)),
                ('gst_info', models.BooleanField(default=False)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.coursefield')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.groopname')),
            ],
        ),
        migrations.AlterField(
            model_name='subscribeplan',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.telegramchannelproduct'),
        ),
        migrations.CreateModel(
            name='TelegramProductQue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.telegramchannelproduct')),
            ],
        ),
    ]
