# Generated by Django 5.1.6 on 2025-03-08 13:08

import account.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_remove_subscribeplan_duration_months_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramchannelproduct',
            name='banner_img',
            field=models.ImageField(null=True, upload_to=account.models.telegram_product_banner),
        ),
        migrations.AddField(
            model_name='telegramchannelproduct',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-02-26 05:22:17'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='telegramchannelproduct',
            name='product_uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='telegramchannelproduct',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
