# Generated by Django 5.1.6 on 2025-03-09 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_telegramchannelproduct_banner_img_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomerProductAns',
            new_name='CustomerPaymentProductAns',
        ),
        migrations.AlterField(
            model_name='customer',
            name='subscribe_start',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='CustomerTelegramProductAns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=300, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.customer')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.telegramchannelproduct')),
            ],
        ),
    ]
