# Generated by Django 5.1.6 on 2025-03-13 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_rename_customerproductans_customerpaymentproductans_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groopname',
            name='group_title',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
