# Generated by Django 5.1.6 on 2025-03-13 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_alter_groopname_group_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GroopName',
            new_name='GroupName',
        ),
    ]
