# Generated by Django 5.1.6 on 2025-03-13 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_rename_groopname_groupname'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupname',
            name='phone_hash_code',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
