# Generated by Django 5.1.6 on 2025-03-15 06:07

import account.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_groupname_phone_hash_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='LockMessaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, null=True)),
                ('product_file', models.ImageField(upload_to=account.models.lock_message_file)),
                ('price', models.CharField(default=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('expire', models.DateTimeField(null=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('categroy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.coursefield')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
