# Generated by Django 5.1.6 on 2025-03-15 06:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_lockmessaging'),
    ]

    operations = [
        migrations.AddField(
            model_name='lockmessaging',
            name='product_uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
