# Generated by Django 5.1.6 on 2025-03-15 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_lockmessaging_product_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='lockmessaging',
            name='desc',
            field=models.TextField(null=True),
        ),
    ]
