# Generated by Django 5.1.6 on 2025-03-15 06:44

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_lockmessaging_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lockmessaging',
            name='product_file',
            field=models.FileField(upload_to=account.models.lock_message_file),
        ),
    ]
