# Generated by Django 5.1.6 on 2025-03-20 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_alter_lockmessaging_product_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp_create',
            field=models.DateTimeField(null=True),
        ),
    ]
