# Generated by Django 5.1.6 on 2025-03-25 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0027_customer_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='lockmessaging',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paymentlink',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='telegramchannelproduct',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
