# Generated by Django 5.1.6 on 2025-04-21 21:02

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0029_cashfreepayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='lockmessaging',
            name='product_img',
            field=models.ImageField(null=True, upload_to=account.models.lock_message_image),
        ),
        migrations.AddField(
            model_name='lockmessaging',
            name='product_video',
            field=models.FileField(null=True, upload_to=account.models.lock_message_video),
        ),
    ]
