# Generated by Django 5.1.6 on 2025-04-25 06:02

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0030_lockmessaging_product_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(null=True, upload_to=account.models.user_image),
        ),
        migrations.AlterField(
            model_name='lockmessaging',
            name='product_file',
            field=models.FileField(null=True, upload_to=account.models.lock_message_file),
        ),
    ]
