# Generated by Django 5.1.6 on 2025-04-27 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0031_user_profile_image_alter_lockmessaging_product_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='subscribeplan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.subscribeplan'),
        ),
    ]
