# Generated by Django 5.1.6 on 2025-05-08 05:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0032_customer_subscribeplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='lockmessaging',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lock_approved_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lockmessaging',
            name='approved_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentlink',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_approved_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentlink',
            name='approved_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lockmessaging',
            name='status',
            field=models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('rejected', 'Rejected')], default='pending'),
        ),
        migrations.AlterField(
            model_name='paymentlink',
            name='status',
            field=models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('rejected', 'Rejected')], default='pending'),
        ),
    ]
