# Generated by Django 5.1.6 on 2025-05-31 10:18

import django.db.models.deletion
import multiselectfield.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0033_lockmessaging_approved_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='clientgoal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.clientgoal'),
        ),
        migrations.CreateModel(
            name='PunchInUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator_name', models.CharField(max_length=20)),
                ('creator_id', models.CharField(max_length=20)),
                ('commission_options', models.CharField(choices=[('other_payment_mode', 'OTHER PAYMENT MODE'), ('upi', 'UPI')], default='upi')),
                ('commission_percent', models.CharField(max_length=20)),
                ('minimum_ticket', models.FloatField()),
                ('maximum_ticket', models.FloatField()),
                ('feature_type', multiselectfield.db.fields.MultiSelectField(choices=[('payment_link', 'PAYMENT_LINK'), ('telegram', 'TELEGRAM'), ('lock_message', 'LOCK_MESSAGE')], max_length=34)),
                ('social_link', models.TextField()),
                ('acquisition_funnel', models.CharField(choices=[('self', 'SELF'), ('organic', 'ORGANIC')], default='self')),
                ('onboarding_reason', models.TextField()),
                ('whatsapp_group', models.CharField(max_length=100)),
                ('document_name', models.CharField(max_length=20)),
                ('document', models.FileField(upload_to='punch_in_documents')),
                ('notes', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='punch_created_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='punch_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
